#!/bin/sh

if [ $# -eq 1 ]; then
    selected=$1
else
    selected=$(find . -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [ -z $selected ]; then
    exit 0
fi

selected_name=$(tmux display-message -p '#S')
tmux_running=$(pgrep tmux)

if [ -z $TMUX ] && [ -z $tmux_running ]; then
    exit 0
fi

echo $selected_name
echo $selected

tmux new-window -t $selected_name -c $selected
