require "opts"
require "launch"

spec("plugins.autopairs")
spec("plugins.bufferline")
spec("plugins.colorizer")
spec("plugins.colorscheme")
spec("plugins.comment")
spec("plugins.dashboard")
spec("plugins.floaterm")
spec("plugins.fugitive")
spec("plugins.gitsigns")
spec("plugins.indent-blankline")
spec("plugins.lsp-config")
spec("plugins.lualine")
spec("plugins.markdown-preview")
spec("plugins.mason")
spec("plugins.merginal")
spec("plugins.neotest")
spec("plugins.nvim-cmp")
spec("plugins.nvim-dap-go")
spec("plugins.nvim-dap")
spec("plugins.nvim-dap-ui")
spec("plugins.nvim-nio")
spec("plugins.nvim-test")
spec("plugins.nvim-tree")
spec("plugins.orgmode")
spec("plugins.plenary")
spec("plugins.rainbow-csv")
spec("plugins.rest-client")
spec("plugins.telescope-fzf")
spec("plugins.telescope")
spec("plugins.telescope-symbols")
spec("plugins.todo-comments")
spec("plugins.treesitter")
spec("plugins.treesitter-textojbects")
spec("plugins.trouble")
spec("plugins.vim-rooter")
spec("plugins.vim-sleuth")
spec("plugins.vim-table-mode")
spec("plugins.which-key")
spec("plugins.yazi")
spec("plugins.url-open")
spec("plugins.harpoon")

require "plugins.lazy"
require "keymaps"
