## Keybindings
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

unbind-key >
bind-key > pipe-pane -o "exec cat >>$HOME/`date`.tmux.log"
unbind-key <
bind-key < pipe-pane

bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind u join-pane -h -t :0
bind o break-pane
unbind '"'
unbind %

# Reload source file
bind-key r source-file ~/.tmux.conf \; display-message "Configuration reloaded"

# Copy and Paste
bind v paste-buffer

unbind-key b
unbind-key y
unbind-key x
bind-key b list-buffers
bind-key y choose-buffer
bind-key x delete-buffer

# TMUX2.1 only
set -g mouse on
bind-key M set -g mouse

# Act like VIM
set-window-option -g mode-keys vi
bind-key j select-pane -D
bind-key k select-pane -U
bind-key h select-pane -L
bind-key l select-pane -R

# Resize pane
bind-key -r -T prefix M-Up    resize-pane -U 5
bind-key -r -T prefix M-Down  resize-pane -D 5
bind-key -r -T prefix M-Left  resize-pane -L 5
bind-key -r -T prefix M-Right resize-pane -R 5

bind-key S setw synchronize-panes

#############

## Options

set -g default-terminal "${TERM}"
# For alacritty
# set -a terminal-features ",alacritty:RGB"

# Updated TMUX Statusbar to Match New Palette ---------------------------
set -g status "on"
set -g status-position "bottom"

set -g status-justify "left"
set -g status-style "bg=black"
set -g status-left-length "50"
set -g status-right-length "50"
set -g status-left-style NONE
set -g status-right-style NONE

# Statusbar appearance (left and right)
set -g status-left " [#S] "
set -g status-right " #(~/.config/tmux/scripts/battery Discharging; ~/.config/tmux/scripts/battery Charging;) | %H:%M | %d-%b-%Y "

setw -g window-status-separator ""
setw -g window-status-format " #I:#W "
setw -g window-status-current-format " [#I:#W] "

##----------------------------------------------------

set -g set-titles on
setw -g monitor-activity off
setw -g mode-keys vi
set -g visual-activity off
set -s escape-time 0

# disable sound bell
set -g bell-action none
# disable visual bell
set -g visual-bell off

set -g history-limit 500000
